#!/usr/bin/env python3
import os, sys

themes_dir = os.path.join(sys.argv[1], 'themes')
project_root = sys.argv[1]
output_file = sys.argv[2]

files = []

# 收集所有主题文件
for root, dirs, filenames in os.walk(themes_dir):
    for f in filenames:
        full = os.path.join(root, f)
        rel = os.path.relpath(full, project_root).replace('\\', '/')
        with open(full, 'r', encoding='utf-8') as fh:
            content = fh.read()
        files.append((rel, content))

# 默认 config.yaml
files.append(('config.yaml', '''title: My Blog
description: A personal blog powered by MiniSSG
baseUrl: https://example.com
sourceDir: posts
outputDir: output
themeDir: themes/minimal
fixHeadings: true
autoNumber: true
'''))

# 示例文章
hello_date = sys.argv[3] if len(sys.argv) > 3 else '2026-01-01'
hello_md = '''---
title: "Hello MiniSSG"
date: {date}
tags: [blog]
---

# Welcome

This is your first post. Start writing!
'''.format(date=hello_date)
files.append(('posts/hello.md', hello_md))

with open(output_file, 'w', encoding='utf-8') as out:
    out.write('// Auto-generated by scripts/embed_theme.py\n')
    out.write('#include <string>\n')
    out.write('#include <vector>\n\n')
    out.write('namespace minissg { namespace cli {\n\n')
    out.write('struct EmbeddedFile { const char* path; const char* content; };\n\n')
    out.write('extern const EmbeddedFile kThemeFiles[] = {\n')

    for idx, (rel, content) in enumerate(files):
        tag = f'EMBED_{idx}'
        out.write(f'    {{"{rel}",\n')
        out.write(f'     R"END_EMBED_{idx}({content})END_EMBED_{idx}"}},\n\n')

    out.write('};\n\n')
    out.write(f'extern const int kThemeFileCount = {len(files)};\n\n')
    out.write('}} // namespace minissg::cli\n')
